[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
sea-orm-migration = { version = "0", features = [
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
] }
