[package]
name = "sktg"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
teloxide = { version = "0.9", features = ["macros", "auto-send"] }

log = "0.4"
pretty_env_logger = "0.4"

chrono = "0.4"
reqwest = "0.11"
