version: "3.9"

services:

  junior:
    build: .
    container_name: sktg-junior

    configs: [ admins ]
    secrets: [ token-junior ]

    environment:
      - BOT_ADMINS_FILE=/admins
      - BOT_TOKEN_FILE=/run/secrets/token-junior

    restart: always
    volumes:
      - database-junior:/var/db

  spinbot:
    build: spinbot
    container_name: sktg-spinbot

    secrets: [ token-spinbot ]

    environment:
      - BOT_TOKEN_FILE=/run/secrets/token-spinbot

    restart: always

configs:
  admins:
    file: ./admins.txt

secrets:
  token-junior:
    file: ./tokens/junior.txt

  token-spinbot:
    file: ./tokens/spinbot.txt

volumes:
  database-junior:
