version: "3.9"
services:
  bot:
    build: .
    container_name: sktg
    environment:
      - BOT_TOKEN_FILE=/run/secrets/token
    restart: always
    secrets:
      - token
    volumes:
      - database:/var/db
secrets:
  token:
    file: ./token.txt
volumes:
  database:
