version: "3.9"
services:
  betalupi:
    container_name: betalupi
    build:
      context: .
      dockerfile: Dockerfile-betalupi
    logging: 
      driver: "none"
    volumes: [ .:/run ]
    user: 1000:1000
    restart: always
  impdro:
    container_name: impdro
    build:
      context: .
      dockerfile: Dockerfile-impdro
    logging:
      driver: "none"
    volumes: [ .:/run ]
    user: 1000:1000
    restart: always
