version: "3.9"
services:
  bot:
    build: .
    container_name: sktg
    environment:
      - BOT_TOKEN_FILE=/run/secrets/token
      - DATABASE_FILE=/run/database/db.sqlite3
      - TMP_DIR=/tmp
    restart: always
    secrets:
      - token
    volumes:
      - database:/run/database
secrets:
  token:
    file: ./token.txt
volumes:
  database:
